// <auto-generated />
using System;
using ICI.ProvaCandidato.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ICI.ProvaCandidato.Dados.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ICI.ProvaCandidato.Web.Models.NoticeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int?>("UserModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserModelId");

                    b.ToTable("NoticeEntity");
                });

            modelBuilder.Entity("ICI.ProvaCandidato.Web.Models.NoticeTagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("NoticeModelId")
                        .HasColumnType("integer");

                    b.Property<int?>("TagEntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NoticeModelId");

                    b.HasIndex("TagEntityId");

                    b.ToTable("NoticeTagEntity");
                });

            modelBuilder.Entity("ICI.ProvaCandidato.Web.Models.TagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TagEntity");
                });

            modelBuilder.Entity("ICI.ProvaCandidato.Web.Models.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Mail")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserModel");
                });

            modelBuilder.Entity("ICI.ProvaCandidato.Web.Models.NoticeEntity", b =>
                {
                    b.HasOne("ICI.ProvaCandidato.Web.Models.UserEntity", "UserModel")
                        .WithMany()
                        .HasForeignKey("UserModelId");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("ICI.ProvaCandidato.Web.Models.NoticeTagEntity", b =>
                {
                    b.HasOne("ICI.ProvaCandidato.Web.Models.NoticeEntity", "NoticeModel")
                        .WithMany()
                        .HasForeignKey("NoticeModelId");

                    b.HasOne("ICI.ProvaCandidato.Web.Models.TagEntity", "TagEntity")
                        .WithMany()
                        .HasForeignKey("TagEntityId");

                    b.Navigation("NoticeModel");

                    b.Navigation("TagEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
